import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "id" | "en" | "ja" | "de";

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: "id", label: "Indonesia", flag: "🇮🇩" },
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "ja", label: "日本語", flag: "🇯🇵" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
];

export const translations = {
  id: {
    // Auth
    welcome: "Selamat Datang",
    loginSubtitle: "Masuk untuk melacak teman di petamu",
    emailOrCode: "Email atau Kode",
    password: "Kata Sandi",
    login: "Masuk",
    register: "Daftar",
    noAccount: "Belum punya akun?",
    haveAccount: "Sudah punya akun?",
    failedConnect: "Gagal terhubung ke server",
    registerTitle: "Buat Akun",
    registerSubtitle: "Bergabung dengan GeoNode",
    name: "Nama",
    email: "Email",
    // Tabs
    map: "Peta",
    friends: "Teman",
    groups: "Grup",
    profile: "Profil",
    // Friends
    friend: "Teman",
    offline: "Offline",
    online: "Online",
    addFriend: "Tambah Teman",
    noFriends: "Belum ada teman",
    noFriendsSub: "Tambahkan teman untuk melihat lokasi mereka",
    // Groups
    group: "Grup",
    noGroups: "Belum ada grup",
    noGroupsSub: "Buat grup untuk berbagi lokasi bersama",
    createGroup: "Buat",
    newGroupName: "Nama grup baru...",
    members: "Anggota",
    addMember: "Tambah Anggota",
    memberCode: "Kode anggota baru...",
    admin: "Admin",
    member: "Anggota",
    kickMember: "Keluarkan",
    makeAdmin: "Jadikan Admin",
    makeMember: "Jadikan Member",
    deleteGroup: "Hapus Grup",
    renameGroup: "Ubah Nama",
    settings: "Pengaturan",
    groupMap: "Peta Grup",
    groupMapTitle: "Peta Lokasi Anggota",
    groupMapSub: "Lokasi anggota yang sedang aktif",
    enableMap: "Aktifkan Peta Grup",
    noLocation: "Belum ada lokasi tersedia",
    // Chat
    typeMessage: "Ketik pesan...",
    deleteMessage: "Hapus Pesan",
    deleteMessageQ: "Hapus pesan ini?",
    delete: "Hapus",
    cancel: "Batal",
    send: "Kirim",
    // Profile
    editProfile: "Edit Profil",
    account: "Akun",
    appearance: "Tampilan",
    language: "Bahasa",
    chooseLanguage: "Pilih Bahasa",
    logout: "Keluar",
    logoutConfirm: "Yakin ingin keluar?",
    save: "Simpan",
    saving: "Menyimpan...",
    profileName: "Nama Tampilan",
    avatarColor: "Warna Avatar",
    copyCode: "Ketuk untuk salin kode unikmu",
    // General
    loading: "Memuat...",
    error: "Error",
    failed: "Gagal",
    success: "Berhasil",
    close: "Tutup",
    ok: "OK",
    confirm: "Konfirmasi",
    yes: "Ya",
    no: "Tidak",
    dangerZone: "ZONA BAHAYA",
    leaveGroup: "Keluar dari Grup",
    failedLoadProfile: "Gagal memuat profil",
    cannotChangeRole: "Tidak bisa mengubah role",
    cannotKick: "Tidak bisa mengeluarkan anggota",
    cannotDeleteGroup: "Tidak bisa menghapus grup",
    cannotDeleteMsg: "Tidak bisa menghapus pesan",
    maintenance: "Sedang Maintenance",
    maintenanceSub: "Server sedang dalam perbaikan. Silakan coba lagi nanti.",
  },
  en: {
    welcome: "Welcome",
    loginSubtitle: "Sign in to track friends on your map",
    emailOrCode: "Email or Code",
    password: "Password",
    login: "Sign In",
    register: "Sign Up",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    failedConnect: "Failed to connect to server",
    registerTitle: "Create Account",
    registerSubtitle: "Join GeoNode",
    name: "Name",
    email: "Email",
    map: "Map",
    friends: "Friends",
    groups: "Groups",
    profile: "Profile",
    friend: "Friend",
    offline: "Offline",
    online: "Online",
    addFriend: "Add Friend",
    noFriends: "No friends yet",
    noFriendsSub: "Add friends to see their location",
    group: "Group",
    noGroups: "No groups yet",
    noGroupsSub: "Create a group to share location together",
    createGroup: "Create",
    newGroupName: "New group name...",
    members: "Members",
    addMember: "Add Member",
    memberCode: "New member code...",
    admin: "Admin",
    member: "Member",
    kickMember: "Remove",
    makeAdmin: "Make Admin",
    makeMember: "Make Member",
    deleteGroup: "Delete Group",
    renameGroup: "Rename",
    settings: "Settings",
    groupMap: "Group Map",
    groupMapTitle: "Member Location Map",
    groupMapSub: "Active member locations",
    enableMap: "Enable Group Map",
    noLocation: "No location available",
    typeMessage: "Type a message...",
    deleteMessage: "Delete Message",
    deleteMessageQ: "Delete this message?",
    delete: "Delete",
    cancel: "Cancel",
    send: "Send",
    editProfile: "Edit Profile",
    account: "Account",
    appearance: "Appearance",
    language: "Language",
    chooseLanguage: "Choose Language",
    logout: "Sign Out",
    logoutConfirm: "Are you sure you want to sign out?",
    save: "Save",
    saving: "Saving...",
    profileName: "Display Name",
    avatarColor: "Avatar Color",
    copyCode: "Tap to copy your unique code",
    loading: "Loading...",
    error: "Error",
    failed: "Failed",
    success: "Success",
    close: "Close",
    ok: "OK",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    dangerZone: "DANGER ZONE",
    leaveGroup: "Leave Group",
    failedLoadProfile: "Failed to load profile",
    cannotChangeRole: "Cannot change role",
    cannotKick: "Cannot remove member",
    cannotDeleteGroup: "Cannot delete group",
    cannotDeleteMsg: "Cannot delete message",
    maintenance: "Under Maintenance",
    maintenanceSub: "Server is under maintenance. Please try again later.",
  },
  ja: {
    welcome: "ようこそ",
    loginSubtitle: "サインインして地図で友達を追跡しよう",
    emailOrCode: "メールまたはコード",
    password: "パスワード",
    login: "サインイン",
    register: "登録",
    noAccount: "アカウントをお持ちでない方？",
    haveAccount: "すでにアカウントをお持ちの方？",
    failedConnect: "サーバーへの接続に失敗しました",
    registerTitle: "アカウント作成",
    registerSubtitle: "GeoNodeに参加する",
    name: "名前",
    email: "メール",
    map: "地図",
    friends: "友達",
    groups: "グループ",
    profile: "プロフィール",
    friend: "友達",
    offline: "オフライン",
    online: "オンライン",
    addFriend: "友達追加",
    noFriends: "まだ友達がいません",
    noFriendsSub: "友達を追加して位置を確認しよう",
    group: "グループ",
    noGroups: "まだグループがありません",
    noGroupsSub: "グループを作って位置を共有しよう",
    createGroup: "作成",
    newGroupName: "新しいグループ名...",
    members: "メンバー",
    addMember: "メンバー追加",
    memberCode: "新メンバーのコード...",
    admin: "管理者",
    member: "メンバー",
    kickMember: "除外",
    makeAdmin: "管理者にする",
    makeMember: "メンバーにする",
    deleteGroup: "グループ削除",
    renameGroup: "名前変更",
    settings: "設定",
    groupMap: "グループ地図",
    groupMapTitle: "メンバー位置地図",
    groupMapSub: "アクティブなメンバーの位置",
    enableMap: "グループ地図を有効化",
    noLocation: "位置情報がありません",
    typeMessage: "メッセージを入力...",
    deleteMessage: "メッセージ削除",
    deleteMessageQ: "このメッセージを削除しますか？",
    delete: "削除",
    cancel: "キャンセル",
    send: "送信",
    editProfile: "プロフィール編集",
    account: "アカウント",
    appearance: "外観",
    language: "言語",
    chooseLanguage: "言語を選択",
    logout: "サインアウト",
    logoutConfirm: "サインアウトしますか？",
    save: "保存",
    saving: "保存中...",
    profileName: "表示名",
    avatarColor: "アバターカラー",
    copyCode: "タップして固有コードをコピー",
    loading: "読み込み中...",
    error: "エラー",
    failed: "失敗",
    success: "成功",
    close: "閉じる",
    ok: "OK",
    confirm: "確認",
    yes: "はい",
    no: "いいえ",
    dangerZone: "危険ゾーン",
    leaveGroup: "グループを離れる",
    failedLoadProfile: "プロフィールの読み込みに失敗しました",
    cannotChangeRole: "役割を変更できません",
    cannotKick: "メンバーを除外できません",
    cannotDeleteGroup: "グループを削除できません",
    cannotDeleteMsg: "メッセージを削除できません",
    maintenance: "メンテナンス中",
    maintenanceSub: "サーバーはメンテナンス中です。後でもう一度お試しください。",
  },
  de: {
    welcome: "Willkommen",
    loginSubtitle: "Melde dich an, um Freunde auf der Karte zu verfolgen",
    emailOrCode: "E-Mail oder Code",
    password: "Passwort",
    login: "Anmelden",
    register: "Registrieren",
    noAccount: "Noch kein Konto?",
    haveAccount: "Bereits ein Konto?",
    failedConnect: "Verbindung zum Server fehlgeschlagen",
    registerTitle: "Konto erstellen",
    registerSubtitle: "GeoNode beitreten",
    name: "Name",
    email: "E-Mail",
    map: "Karte",
    friends: "Freunde",
    groups: "Gruppen",
    profile: "Profil",
    friend: "Freund",
    offline: "Offline",
    online: "Online",
    addFriend: "Freund hinzufügen",
    noFriends: "Noch keine Freunde",
    noFriendsSub: "Füge Freunde hinzu, um ihre Standorte zu sehen",
    group: "Gruppe",
    noGroups: "Noch keine Gruppen",
    noGroupsSub: "Erstelle eine Gruppe, um Standorte zu teilen",
    createGroup: "Erstellen",
    newGroupName: "Neuer Gruppenname...",
    members: "Mitglieder",
    addMember: "Mitglied hinzufügen",
    memberCode: "Code des neuen Mitglieds...",
    admin: "Admin",
    member: "Mitglied",
    kickMember: "Entfernen",
    makeAdmin: "Zum Admin machen",
    makeMember: "Zum Mitglied machen",
    deleteGroup: "Gruppe löschen",
    renameGroup: "Umbenennen",
    settings: "Einstellungen",
    groupMap: "Gruppenkarte",
    groupMapTitle: "Mitglieder-Standortkarte",
    groupMapSub: "Standorte aktiver Mitglieder",
    enableMap: "Gruppenkarte aktivieren",
    noLocation: "Kein Standort verfügbar",
    typeMessage: "Nachricht eingeben...",
    deleteMessage: "Nachricht löschen",
    deleteMessageQ: "Diese Nachricht löschen?",
    delete: "Löschen",
    cancel: "Abbrechen",
    send: "Senden",
    editProfile: "Profil bearbeiten",
    account: "Konto",
    appearance: "Erscheinungsbild",
    language: "Sprache",
    chooseLanguage: "Sprache wählen",
    logout: "Abmelden",
    logoutConfirm: "Möchtest du dich wirklich abmelden?",
    save: "Speichern",
    saving: "Speichern...",
    profileName: "Anzeigename",
    avatarColor: "Avatar-Farbe",
    copyCode: "Tippen, um den einzigartigen Code zu kopieren",
    loading: "Laden...",
    error: "Fehler",
    failed: "Fehlgeschlagen",
    success: "Erfolg",
    close: "Schließen",
    ok: "OK",
    confirm: "Bestätigen",
    yes: "Ja",
    no: "Nein",
    dangerZone: "GEFAHRENZONE",
    leaveGroup: "Gruppe verlassen",
    failedLoadProfile: "Profil konnte nicht geladen werden",
    cannotChangeRole: "Rolle kann nicht geändert werden",
    cannotKick: "Mitglied kann nicht entfernt werden",
    cannotDeleteGroup: "Gruppe kann nicht gelöscht werden",
    cannotDeleteMsg: "Nachricht kann nicht gelöscht werden",
    maintenance: "Wartung",
    maintenanceSub: "Server wird gewartet. Bitte versuche es später erneut.",
  },
};

type Translations = typeof translations.id;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("id");

  useEffect(() => {
    AsyncStorage.getItem("gl_language").then((stored) => {
      if (stored && (stored === "id" || stored === "en" || stored === "ja" || stored === "de")) {
        setLanguageState(stored as Language);
      }
    });
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem("gl_language", lang);
  };

  const t = translations[language] as Translations;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be inside LanguageProvider");
  return ctx;
}
